# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: publish
on: [ workflow_dispatch ]

env:
  MINECRAFT_VERSIONS: |
    1.19.4
  JAVA_VERSION: 17
  VERSION_TYPE: release
  RELEASE_PREFIX: |
    [1.19.4] Igneous Machines

jobs:
  publish:
    strategy:
      matrix:
        # Use these Java versions
        java: [
          17,    # Current Java LTS & minimum supported by Minecraft
        ]
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'microsoft'
      - name: make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build
      - name: capture build artifacts
        if: ${{ runner.os == 'Linux' && matrix.java == '17' }} # Only upload artifacts built from latest java on one OS
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: build/libs/
      - name: Set variables
        run: |
          VER=$(./gradlew -q projectVersion)
          echo "VERSION=$VER" >> $GITHUB_ENV
      - name: Publish (CurseForge/Modrinth/GitHub)
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: i4mUEhXw
          modrinth-token: ${{ secrets.TOKEN_MODRINTH }}

          curseforge-id: 881761
          curseforge-token: ${{ secrets.TOKEN_CURSEFORGE }}

          github-tag: 1.19.4
          github-generate-changelog: true
          github-token: ${{ secrets.TOKEN_GITHUB }}

          files: |
            build/libs/!(*-@(dev|sources|javadoc)).jar

          name: ${{ env.RELEASE_PREFIX }} ${{ env.VERSION }}
          version: ${{ env.VERSION }}
          version-type: ${{ env.VERSION_TYPE }}
          changelog-file: CHANGELOG.md

          loaders: fabric
          game-versions: ${{ env.MINECRAFT_VERSIONS }}
          java: ${{ env.JAVA_VERSION }}

          dependencies: |
            fabric-api(required){modrinth:P7dR8mSH}{curseforge:306612}#(ignore:github)
